/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.flink.streaming.examples;

import org.apache.flink.api.common.eventtime.WatermarkStrategy;
import org.apache.flink.api.common.typeinfo.TypeHint;
import org.apache.flink.api.common.typeinfo.TypeInformation;
import org.apache.flink.api.java.tuple.Tuple3;
import org.apache.flink.streaming.api.datastream.DataStream;
import org.apache.flink.streaming.api.environment.StreamExecutionEnvironment;
import org.apache.flink.table.data.RowData;
import org.apache.flink.table.runtime.generated.AggsHandleFunction;

import java.time.Duration;

/**
 * V5: Show how Flink Table API does windowed Local-Global COUNT(*) internally, implemented
 * with the DataStream API only.
 *
 * <p>V5 produces the same logical output as V4 (one row per (key, window) when the window
 * closes, with retraction-style re-fires on late events), but does NOT use the Table API DSL.
 * Instead, V5 illustrates the two main pieces the Table API uses internally:
 *
 * <ol>
 *   <li><b>An {@link AggsHandleFunction} for the aggregation logic itself.</b> In the real
 *       Table API this class is generated by {@code AggsHandlerCodeGenerator} from the SQL's
 *       {@code AggregateCall} list. The generated code is compiled by Janino at task {@code
 *       open()} time. V5 hand-writes the equivalent of what codegen would produce for {@code
 *       COUNT(*)}: {@link CountStarAggsHandleFunctionV5}.
 *   <li><b>Two operators that drive the aggregation: a LOCAL pre-aggregator and a GLOBAL final
 *       aggregator.</b> The real Table API uses {@code LocalSlicingWindowAggOperator}
 *       (non-keyed, in-memory buffer flushed on watermark advance) for local and {@code
 *       WindowAggOperator} (keyed, with timer-driven window firing) for global. V5 mirrors
 *       both as {@link LocalWindowAggregateOperatorV5} and {@link
 *       GlobalWindowAggregateFunctionV5}.
 * </ol>
 *
 * <h2>Layout — one class per concept, all named {@code xxxV5}</h2>
 *
 * <pre>
 *   TwoPhaseCountDeduplicatedEventTimeV5      ◄── this file: just main() and pipeline wiring
 *   EventToRowDataMapV5                       ─── Tuple3 → RowData[key]
 *   KeyExtractorV5                            ─── RowData → bundle key (String)
 *   CountStarAggsHandleFunctionV5             ─── hand-written codegen output for COUNT(*)
 *   LocalWindowAggregateOperatorV5            ─── non-keyed pre-aggregator (heap buffer)
 *   GlobalWindowAggregateFunctionV5           ─── keyed final aggregator + changelog emission
 * </pre>
 *
 * <h2>Overall flow</h2>
 *
 * <pre>
 *  source: Tuple3&lt;key, value, eventTimeMillis&gt;
 *    │
 *    ▼  map → RowData[key:STRING]              {@link EventToRowDataMapV5}
 *  rowStream
 *    │
 *    ▼  .transform(LocalWindowAggregateOperatorV5)    ◄── NON-KEYED
 *  ┌─────────────────────────────────────────────────────────┐
 *  │ {@link LocalWindowAggregateOperatorV5}                  │
 *  │   in-memory buffer per (bundleKey, windowStart)         │
 *  │   flush on watermark advance + pre-barrier              │
 *  │   no late-data handling here                            │
 *  └─────────────────────────────────────────────────────────┘
 *    │  Output: RowData[key, windowStart, partialCount]
 *    │
 *    ▼  keyBy(key)                            ◄── THE ONLY SHUFFLE
 *  ┌─────────────────────────────────────────────────────────┐
 *  │ {@link GlobalWindowAggregateFunctionV5}                 │
 *  │   per (key, windowStart) MapState accumulator           │
 *  │   on windowEnd timer       → emit +I                    │
 *  │   on late merge            → emit -U / +U               │
 *  │   on cleanup timer         → drop state                 │
 *  └─────────────────────────────────────────────────────────┘
 *    │  Output: RowData[key, windowStart, total] with RowKind
 *    │
 *    ▼
 *  print
 * </pre>
 *
 * <h2>Aggregation logic vs operator machinery</h2>
 *
 * <p>The whole point of V5 is to make this separation visible:
 *
 * <ul>
 *   <li>{@link CountStarAggsHandleFunctionV5} contains <i>only</i> the aggregation arithmetic
 *       — create / accumulate / retract / merge / getValue. This is the part the Table API
 *       codegen produces from the SQL aggregate calls. Different SQL would produce different
 *       handler implementations but the SAME outer operators.
 *   <li>{@link LocalWindowAggregateOperatorV5} and {@link GlobalWindowAggregateFunctionV5}
 *       contain <i>only</i> the windowing, state, timer, and changelog machinery. They are
 *       aggregate-agnostic — they call {@code accumulate} / {@code merge} / {@code getValue}
 *       on whatever {@link AggsHandleFunction} they're given.
 * </ul>
 *
 * <p>That's the Table API's design: codegen handles the aggregation arithmetic, a fixed set of
 * operator classes handle execution.
 *
 * <h2>Late-data handling — concentrated in the global stage</h2>
 *
 * <p>The local stage has no concept of "late data". It just buffers and flushes; a late event
 * gets added to the in-memory buffer (creating a fresh accumulator at the original {@code
 * windowStart} if needed) and emitted on the next watermark advance like any other event.
 *
 * <p>All late-data semantics (allow-lateness, late-fire, drop-past-lateness) live in {@link
 * GlobalWindowAggregateFunctionV5#processElement}. The key correctness property:
 * <b>{@code windowStart} is preserved end-to-end</b> from the local stage into the global
 * stage's per-window state, so a late event always updates its original window's accumulator
 * — never bleeds into the next window.
 *
 * <p>See {@link GlobalWindowAggregateFunctionV5}'s JavaDoc for a worked example trace of the
 * late-data path.
 *
 * <h2>What V5 omits from the real Table API</h2>
 *
 * <ul>
 *   <li><b>Slicing.</b> The real Table API splits time into slices (for hopping/cumulative
 *       windows) and pre-aggregates per slice. V5 uses tumbling-only — slice == window —
 *       which is correct for the 1-minute tumbling case used here.
 *   <li><b>RecordCounter + equaliser.</b> For COUNT(*) the count itself acts as the record
 *       counter (count==0 ⇒ no contribution), and the global stage emits UPDATE_BEFORE +
 *       UPDATE_AFTER on re-fires using a simple "previous value" comparison. The real Table
 *       API short-circuits no-op updates via a generated equaliser.
 *   <li><b>The actual codegen invocation.</b> V5 hand-writes {@link
 *       CountStarAggsHandleFunctionV5} instead of producing it via {@code
 *       AggsHandlerCodeGenerator} (which would require wiring a Calcite {@code RelBuilder},
 *       {@code AggregateInfoList}, and the planner's code splitter — orthogonal to
 *       understanding the local-global mechanic).
 *   <li><b>Side-output for past-lateness events.</b> Past-lateness events are dropped
 *       silently, just like the real Table API.
 * </ul>
 */
public class TwoPhaseCountDeduplicatedEventTimeV5 {

    /** Window duration, matching V4's {@code Tumble.over(lit(1).minutes())}. */
    public static final long WINDOW_SIZE_MS = Duration.ofMinutes(1).toMillis();

    public static void main(String[] args) throws Exception {

        StreamExecutionEnvironment env = StreamExecutionEnvironment.createLocalEnvironment();
        env.setParallelism(2); // multi-subtask so the local-global exchange is visible

        // ─────────────────────────────────────────────────────────────────────
        // Source — reuse the same delayed-events source as V2/V3/V4 so the
        // input behaviour matches exactly. Batch 1 fires the window normally;
        // Batch 2 emits late events to exercise the re-fire path.
        // ─────────────────────────────────────────────────────────────────────
        DataStream<Tuple3<String, String, Long>> rawInput =
                env.addSource(
                        new TwoPhaseCountDeduplicatedEventTimeV2.DelayedEventsSource(),
                        TypeInformation.of(new TypeHint<Tuple3<String, String, Long>>() {}));

        // Attach event-time timestamps + watermark identical to V2.
        DataStream<Tuple3<String, String, Long>> input =
                rawInput.assignTimestampsAndWatermarks(
                        WatermarkStrategy
                                .<Tuple3<String, String, Long>>forBoundedOutOfOrderness(
                                        Duration.ofSeconds(5))
                                .withTimestampAssigner((event, ts) -> event.f2)
                                .withIdleness(Duration.ofMinutes(1)));

        // Step 1: convert Tuple3 -> RowData[key].
        DataStream<RowData> rowStream =
                input.map(new EventToRowDataMapV5()).returns(TypeInformation.of(RowData.class));

        // Step 2: LOCAL stage — non-keyed, no preceding keyBy.
        DataStream<RowData> localPartials =
                rowStream.transform(
                        "local-window-aggregate",
                        TypeInformation.of(RowData.class),
                        new LocalWindowAggregateOperatorV5(new KeyExtractorV5(), WINDOW_SIZE_MS));

        // Step 3: GLOBAL stage — keyed via the only hash exchange in the pipeline.
        DataStream<RowData> finalResults =
                localPartials
                        .keyBy(new KeyExtractorV5())
                        .process(new GlobalWindowAggregateFunctionV5())
                        .returns(TypeInformation.of(RowData.class))
                        .name("global-window-aggregate");

        // Print with row-kind prefix so retractions are visible.
        finalResults.map(TwoPhaseCountDeduplicatedEventTimeV5::formatRow).print("RESULT");

        env.execute("Two-Phase Count V5 (Local-Global via AggsHandleFunction)");
    }

    /** Format helper so we can see RowKind in stdout. */
    public static String formatRow(RowData row) {
        return row.getRowKind().shortString()
                + "["
                + row.getString(0)
                + ", windowStart="
                + row.getLong(1)
                + ", count="
                + row.getLong(2)
                + "]";
    }
}
